In [5]:
import numpy as np

feature_vector = 5 + np.arange(12)

np.random.seed(42)

feature_matrix = np.random.randint(0, 10, (3, 4))

print(f"Feature Vector: size:{feature_vector.size}",
      f"ndim:{feature_vector.ndim}", 
      f"shape:{feature_vector.shape}",
      f"data type:{feature_vector.dtype}")
print(f"Feature Matrix: size:{feature_matrix.size}",
      f"ndim:{feature_matrix.ndim}", 
      f"shape:{feature_matrix.shape}",
      f"data type:{feature_matrix.dtype}") 

Feature Vector: size:12 ndim:1 shape:(12,) data type:int32
Feature Matrix: size:12 ndim:2 shape:(3, 4) data type:int32


In [7]:
print(f"feature_matrix:\n{feature_matrix}")
print(f"value in row 2 and column 3 of feature_matrix:{feature_matrix[1,2]}")
print(f"row 1 of feature_matrix:{feature_matrix[0]}")
print(f"last column of feature_matrix:{feature_matrix[:,-1]}")
print(f"top right 2x2 submatrix of feature_matrix:\n{feature_matrix[:2, -2:]}")


feature_matrix:
[[6 3 7 4]
 [6 9 2 6]
 [7 4 3 7]]
value in row 2 and column 3 of feature_matrix:2
row 1 of feature_matrix:[6 3 7 4]
last column of feature_matrix:[4 6 7]
top right 2x2 submatrix of feature_matrix:
[[7 4]
 [2 6]]


In [8]:
feature_vector = feature_vector.reshape(4, 3)
print(f"feature_vector shape:{feature_vector.shape}")
print(f"feature_matrix flattened:\n{feature_matrix.flatten()}")

feature_vector shape:(4, 3)
feature_matrix flattened:
[6 3 7 4 6 9 2 6 7 4 3 7]


In [14]:
new_matrix = np.ones((3, 4))
vstacked_matrix = np.vstack((feature_matrix, new_matrix))
print(f"vstacked_matrix:\n{vstacked_matrix}")
hstacked_matrix = np.hstack((feature_matrix, new_matrix))
print(f"hstacked_matrix:\n{hstacked_matrix}")
new_vector = np.array([10, 20, 30]).reshape(3, 1)
stacked_matrix = np.hstack((feature_matrix, new_vector))
print(f"stacked_matrix:\n{stacked_matrix}")

vstacked_matrix:
[[6. 3. 7. 4.]
 [6. 9. 2. 6.]
 [7. 4. 3. 7.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
hstacked_matrix:
[[6. 3. 7. 4. 1. 1. 1. 1.]
 [6. 9. 2. 6. 1. 1. 1. 1.]
 [7. 4. 3. 7. 1. 1. 1. 1.]]
stacked_matrix:
[[ 6  3  7  4 10]
 [ 6  9  2  6 20]
 [ 7  4  3  7 30]]


In [25]:
np.random.seed(101)
scores = np.random.randint(50, 101, (15, 3))
exam_means = np.mean(scores, axis=0)
print(f"exam means:\n{exam_means}")
exam_stds = np.std(scores, axis=0)
print(f"exam stds:\n{exam_stds}")
print(f"max scores in exam 3:\n{np.max(scores, axis=0)[2]}")
print(f"students means:\n{np.mean(scores, axis=1)}")
curved_scores = scores + [5,0,0]
print(f"first exam scores plus 5:\n{curved_scores}")
normized_scores = (scores - exam_means) / exam_stds
print(f"normalized scores:\n exam means:{np.mean(normized_scores, axis=0)}",
      f"exam stds:{np.std(normized_scores, axis=0)}")


exam means:
[76.73333333 70.46666667 73.93333333]
exam stds:
[15.91840305 16.38644426 12.01369589]
max scores in exam 3:
96
students means:
[69.66666667 63.33333333 73.         78.         74.66666667 65.33333333
 86.         78.         78.66666667 63.66666667 82.33333333 66.66666667
 80.33333333 77.33333333 68.66666667]
first exam scores plus 5:
[[ 86  61  67]
 [ 61  73  61]
 [102  59  63]
 [ 95  54  90]
 [ 83  50  96]
 [ 60  62  79]
 [ 95  99  69]
 [102  58  79]
 [ 89  94  58]
 [ 74  60  62]
 [ 86  93  73]
 [ 55  91  59]
 [102  58  86]
 [ 74  85  78]
 [ 62  60  89]]
normalized scores:
 exam means:[-7.40148683e-17 -9.62193288e-17 -2.66453526e-16] exam stds:[1. 1. 1.]


In [ ]:
print(f"scores:\n{scores}")
greater_than_95 = scores > 95
print(f"number of scores greater than 95:\n{np.sum(greater_than_95)}")
high_performance_scores = scores[greater_than_95]
print(f"high performance scores:\n{high_performance_scores}")
print(f"exam 2 mean for exam 1 scores greater than 70:\n{np.mean(scores[scores[:, 0] > 70, 1])}")
pass_fail = np.mean(scores, axis=1) > 65
print(f"pass/fail:\n{pass_fail}")
execlent_students = scores[np.all(scores > 90, axis=1)]
if execlent_students.size == 0:
    execlent_students = "No students with all scores above 90"

print(f"execlent students:\n{execlent_students}")

scores:
[[81 61 67]
 [56 73 61]
 [97 59 63]
 [90 54 90]
 [78 50 96]
 [55 62 79]
 [90 99 69]
 [97 58 79]
 [84 94 58]
 [69 60 62]
 [81 93 73]
 [50 91 59]
 [97 58 86]
 [69 85 78]
 [57 60 89]]
number of scores greater than 95:
5
high performance scores:
[97 96 99 97 97]
exam 2 mean for exam 1 scores greater than 70:
69.55555555555556
pass/fail:
[ True False  True  True  True  True  True  True  True False  True  True
  True  True  True]
execlent students:
ssafds
